[package]
name = "wave_rush"
version = "0.1.0"
edition = "2021"

[dependencies]
aligned-vec = "0.6.1"
fallible-iterator = "0.3.0"
thiserror = "2.0.11"

[dev-dependencies]
rand = "0.9.0"

[profile.release]
codegen-units = 1
opt-level = 3
debug = true
